# Generated by Django 3.1.3 on 2020-11-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='state',
        ),
    ]
